// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package ch.admin.eid.didresolver.didtoolbox;

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.ConcurrentHashMap
import android.os.Build
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicLong

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    @JvmField var capacity: Int = 0
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

    companion object {
        internal fun alloc(size: Int = 0) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_didtoolbox_rustbuffer_alloc(size, status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: Int, len: Int, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity
            buf.len = len
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_didtoolbox_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setInt(0, value.capacity)
        pointer.setInt(4, value.len)
        pointer.setPointer(8, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getInt(0))
        value.writeField("len", pointer.getInt(4))
        value.writeField("data", pointer.getPointer(8))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): Int

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity.toLong()).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == 0.toByte()
    }

    fun isError(): Boolean {
        return code == 1.toByte()
    }

    fun isPanic(): Boolean {
        return code == 2.toByte()
    }
}

class InternalException(message: String) : Exception(message)

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus();
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

// UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback);
}

// IntegerType that matches Rust's `usize` / C's `size_t`
public class USize(value: Long = 0) : IntegerType(Native.SIZE_T_SIZE, value, true) {
    // This is needed to fill in the gaps of IntegerType's implementation of Number for Kotlin.
    override fun toByte() = toInt().toByte()
    // Needed until https://youtrack.jetbrains.com/issue/KT-47902 is fixed.
    @Deprecated("`toInt().toChar()` is deprecated")
    override fun toChar() = toInt().toChar()
    override fun toShort() = toInt().toShort()

    fun writeToBuffer(buf: ByteBuffer) {
        // Make sure we always write usize integers using native byte-order, since they may be
        // casted to pointer values
        buf.order(ByteOrder.nativeOrder())
        try {
            when (Native.SIZE_T_SIZE) {
                4 -> buf.putInt(toInt())
                8 -> buf.putLong(toLong())
                else -> throw RuntimeException("Invalid SIZE_T_SIZE: ${Native.SIZE_T_SIZE}")
            }
        } finally {
            buf.order(ByteOrder.BIG_ENDIAN)
        }
    }

    companion object {
        val size: Int
            get() = Native.SIZE_T_SIZE

        fun readFromBuffer(buf: ByteBuffer) : USize {
            // Make sure we always read usize integers using native byte-order, since they may be
            // casted from pointer values
            buf.order(ByteOrder.nativeOrder())
            try {
                return when (Native.SIZE_T_SIZE) {
                    4 -> USize(buf.getInt().toLong())
                    8 -> USize(buf.getLong())
                    else -> throw RuntimeException("Invalid SIZE_T_SIZE: ${Native.SIZE_T_SIZE}")
                }
            } finally {
                buf.order(ByteOrder.BIG_ENDIAN)
            }
        }
    }
}


// Map handles to objects
//
// This is used when the Rust code expects an opaque pointer to represent some foreign object.
// Normally we would pass a pointer to the object, but JNA doesn't support getting a pointer from an
// object reference , nor does it support leaking a reference to Rust.
//
// Instead, this class maps USize values to objects so that we can pass a pointer-sized type to
// Rust when it needs an opaque pointer.
//
// TODO: refactor callbacks to use this class
internal class UniFfiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<USize, T>()
    // Use AtomicInteger for our counter, since we may be on a 32-bit system.  4 billion possible
    // values seems like enough. If somehow we generate 4 billion handles, then this will wrap
    // around back to zero and we can assume the first handle generated will have been dropped by
    // then.
    private val counter = java.util.concurrent.atomic.AtomicInteger(0)

    val size: Int
        get() = map.size

    fun insert(obj: T): USize {
        val handle = USize(counter.getAndAdd(1).toLong())
        map.put(handle, obj)
        return handle
    }

    fun get(handle: USize): T? {
        return map.get(handle)
    }

    fun remove(handle: USize): T? {
        return map.remove(handle)
    }
}

// FFI type for Rust future continuations
internal interface UniFffiRustFutureContinuationCallbackType : com.sun.jna.Callback {
    fun callback(continuationHandle: USize, pollResult: Byte);
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "didresolver"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            loadIndirect<UniffiLib>(componentName = "didtoolbox")
            .also { lib: UniffiLib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                }
        }
        
        // The Cleaner for the whole library
        internal val CLEANER: UniffiCleaner by lazy {
            UniffiCleaner.create()
        }
    }

    fun uniffi_didtoolbox_fn_clone_diddoc(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_free_diddoc(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_didtoolbox_fn_constructor_diddoc_from_json(`jsonContent`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_method_diddoc_get_assertion_method(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_didtoolbox_fn_method_diddoc_get_authentication(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_didtoolbox_fn_method_diddoc_get_capability_delegation(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_didtoolbox_fn_method_diddoc_get_capability_invocation(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_didtoolbox_fn_method_diddoc_get_context(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_didtoolbox_fn_method_diddoc_get_controller(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_didtoolbox_fn_method_diddoc_get_deactivated(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun uniffi_didtoolbox_fn_method_diddoc_get_id(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_didtoolbox_fn_method_diddoc_get_verification_method(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_didtoolbox_fn_clone_diddocumentstate(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_free_diddocumentstate(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_didtoolbox_fn_constructor_diddocumentstate_from(`didLog`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_method_diddocumentstate_validate(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_method_diddocumentstate_validate_with_scid(`ptr`: Pointer,`scid`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_clone_ed25519keypair(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_free_ed25519keypair(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_didtoolbox_fn_constructor_ed25519keypair_from(`signingKeyMultibase`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_constructor_ed25519keypair_generate(uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_method_ed25519keypair_get_signing_key(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_method_ed25519keypair_get_verifying_key(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_method_ed25519keypair_sign(`ptr`: Pointer,`message`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_clone_ed25519signature(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_free_ed25519signature(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_didtoolbox_fn_constructor_ed25519signature_from_multibase(`multibase`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_method_ed25519signature_to_multibase(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_didtoolbox_fn_clone_ed25519signingkey(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_free_ed25519signingkey(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_didtoolbox_fn_constructor_ed25519signingkey_from_multibase(`multibase`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_method_ed25519signingkey_to_multibase(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_didtoolbox_fn_clone_ed25519verifyingkey(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_free_ed25519verifyingkey(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_didtoolbox_fn_constructor_ed25519verifyingkey_from_multibase(`multibase`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_method_ed25519verifyingkey_to_multibase(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_didtoolbox_fn_clone_trustdidweb(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_free_trustdidweb(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_didtoolbox_fn_constructor_trustdidweb_create(`url`: RustBuffer.ByValue,`keyPair`: Pointer,`allowHttp`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_constructor_trustdidweb_deactivate(`didTdw`: RustBuffer.ByValue,`didLog`: RustBuffer.ByValue,`keyPair`: Pointer,`allowHttp`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_constructor_trustdidweb_read(`didTdw`: RustBuffer.ByValue,`allowHttp`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_constructor_trustdidweb_update(`didTdw`: RustBuffer.ByValue,`didLog`: RustBuffer.ByValue,`didDoc`: RustBuffer.ByValue,`keyPair`: Pointer,`allowHttp`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_method_trustdidweb_get_did(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_didtoolbox_fn_method_trustdidweb_get_did_doc(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_didtoolbox_fn_method_trustdidweb_get_did_log(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_didtoolbox_fn_clone_trustdidwebprocessor(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_free_trustdidwebprocessor(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_didtoolbox_fn_constructor_trustdidwebprocessor_new(uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_constructor_trustdidwebprocessor_new_with_api_key(`apiKey`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_didtoolbox_fn_method_trustdidwebprocessor_create(`ptr`: Pointer,`url`: RustBuffer.ByValue,`keyPair`: Pointer,`allowHttp`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_didtoolbox_fn_method_trustdidwebprocessor_deactivate(`ptr`: Pointer,`didTdw`: RustBuffer.ByValue,`keyPair`: Pointer,`allowHttp`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_didtoolbox_fn_method_trustdidwebprocessor_read(`ptr`: Pointer,`didTdw`: RustBuffer.ByValue,`allowHttp`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_didtoolbox_fn_method_trustdidwebprocessor_update(`ptr`: Pointer,`didTdw`: RustBuffer.ByValue,`didDoc`: RustBuffer.ByValue,`keyPair`: Pointer,`allowHttp`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_didtoolbox_rustbuffer_alloc(`size`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_didtoolbox_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_didtoolbox_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_didtoolbox_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_didtoolbox_rust_future_poll_u8(`handle`: Pointer,`callback`: UniFffiRustFutureContinuationCallbackType,`callbackData`: USize,
    ): Unit
    fun ffi_didtoolbox_rust_future_cancel_u8(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_free_u8(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_complete_u8(`handle`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_didtoolbox_rust_future_poll_i8(`handle`: Pointer,`callback`: UniFffiRustFutureContinuationCallbackType,`callbackData`: USize,
    ): Unit
    fun ffi_didtoolbox_rust_future_cancel_i8(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_free_i8(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_complete_i8(`handle`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_didtoolbox_rust_future_poll_u16(`handle`: Pointer,`callback`: UniFffiRustFutureContinuationCallbackType,`callbackData`: USize,
    ): Unit
    fun ffi_didtoolbox_rust_future_cancel_u16(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_free_u16(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_complete_u16(`handle`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_didtoolbox_rust_future_poll_i16(`handle`: Pointer,`callback`: UniFffiRustFutureContinuationCallbackType,`callbackData`: USize,
    ): Unit
    fun ffi_didtoolbox_rust_future_cancel_i16(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_free_i16(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_complete_i16(`handle`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_didtoolbox_rust_future_poll_u32(`handle`: Pointer,`callback`: UniFffiRustFutureContinuationCallbackType,`callbackData`: USize,
    ): Unit
    fun ffi_didtoolbox_rust_future_cancel_u32(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_free_u32(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_complete_u32(`handle`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_didtoolbox_rust_future_poll_i32(`handle`: Pointer,`callback`: UniFffiRustFutureContinuationCallbackType,`callbackData`: USize,
    ): Unit
    fun ffi_didtoolbox_rust_future_cancel_i32(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_free_i32(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_complete_i32(`handle`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_didtoolbox_rust_future_poll_u64(`handle`: Pointer,`callback`: UniFffiRustFutureContinuationCallbackType,`callbackData`: USize,
    ): Unit
    fun ffi_didtoolbox_rust_future_cancel_u64(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_free_u64(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_complete_u64(`handle`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_didtoolbox_rust_future_poll_i64(`handle`: Pointer,`callback`: UniFffiRustFutureContinuationCallbackType,`callbackData`: USize,
    ): Unit
    fun ffi_didtoolbox_rust_future_cancel_i64(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_free_i64(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_complete_i64(`handle`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_didtoolbox_rust_future_poll_f32(`handle`: Pointer,`callback`: UniFffiRustFutureContinuationCallbackType,`callbackData`: USize,
    ): Unit
    fun ffi_didtoolbox_rust_future_cancel_f32(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_free_f32(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_complete_f32(`handle`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    fun ffi_didtoolbox_rust_future_poll_f64(`handle`: Pointer,`callback`: UniFffiRustFutureContinuationCallbackType,`callbackData`: USize,
    ): Unit
    fun ffi_didtoolbox_rust_future_cancel_f64(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_free_f64(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_complete_f64(`handle`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    fun ffi_didtoolbox_rust_future_poll_pointer(`handle`: Pointer,`callback`: UniFffiRustFutureContinuationCallbackType,`callbackData`: USize,
    ): Unit
    fun ffi_didtoolbox_rust_future_cancel_pointer(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_free_pointer(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_complete_pointer(`handle`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun ffi_didtoolbox_rust_future_poll_rust_buffer(`handle`: Pointer,`callback`: UniFffiRustFutureContinuationCallbackType,`callbackData`: USize,
    ): Unit
    fun ffi_didtoolbox_rust_future_cancel_rust_buffer(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_free_rust_buffer(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_complete_rust_buffer(`handle`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_didtoolbox_rust_future_poll_void(`handle`: Pointer,`callback`: UniFffiRustFutureContinuationCallbackType,`callbackData`: USize,
    ): Unit
    fun ffi_didtoolbox_rust_future_cancel_void(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_free_void(`handle`: Pointer,
    ): Unit
    fun ffi_didtoolbox_rust_future_complete_void(`handle`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_didtoolbox_checksum_method_diddoc_get_assertion_method(
    ): Short
    fun uniffi_didtoolbox_checksum_method_diddoc_get_authentication(
    ): Short
    fun uniffi_didtoolbox_checksum_method_diddoc_get_capability_delegation(
    ): Short
    fun uniffi_didtoolbox_checksum_method_diddoc_get_capability_invocation(
    ): Short
    fun uniffi_didtoolbox_checksum_method_diddoc_get_context(
    ): Short
    fun uniffi_didtoolbox_checksum_method_diddoc_get_controller(
    ): Short
    fun uniffi_didtoolbox_checksum_method_diddoc_get_deactivated(
    ): Short
    fun uniffi_didtoolbox_checksum_method_diddoc_get_id(
    ): Short
    fun uniffi_didtoolbox_checksum_method_diddoc_get_verification_method(
    ): Short
    fun uniffi_didtoolbox_checksum_method_diddocumentstate_validate(
    ): Short
    fun uniffi_didtoolbox_checksum_method_diddocumentstate_validate_with_scid(
    ): Short
    fun uniffi_didtoolbox_checksum_method_ed25519keypair_get_signing_key(
    ): Short
    fun uniffi_didtoolbox_checksum_method_ed25519keypair_get_verifying_key(
    ): Short
    fun uniffi_didtoolbox_checksum_method_ed25519keypair_sign(
    ): Short
    fun uniffi_didtoolbox_checksum_method_ed25519signature_to_multibase(
    ): Short
    fun uniffi_didtoolbox_checksum_method_ed25519signingkey_to_multibase(
    ): Short
    fun uniffi_didtoolbox_checksum_method_ed25519verifyingkey_to_multibase(
    ): Short
    fun uniffi_didtoolbox_checksum_method_trustdidweb_get_did(
    ): Short
    fun uniffi_didtoolbox_checksum_method_trustdidweb_get_did_doc(
    ): Short
    fun uniffi_didtoolbox_checksum_method_trustdidweb_get_did_log(
    ): Short
    fun uniffi_didtoolbox_checksum_method_trustdidwebprocessor_create(
    ): Short
    fun uniffi_didtoolbox_checksum_method_trustdidwebprocessor_deactivate(
    ): Short
    fun uniffi_didtoolbox_checksum_method_trustdidwebprocessor_read(
    ): Short
    fun uniffi_didtoolbox_checksum_method_trustdidwebprocessor_update(
    ): Short
    fun uniffi_didtoolbox_checksum_constructor_diddoc_from_json(
    ): Short
    fun uniffi_didtoolbox_checksum_constructor_diddocumentstate_from(
    ): Short
    fun uniffi_didtoolbox_checksum_constructor_ed25519keypair_from(
    ): Short
    fun uniffi_didtoolbox_checksum_constructor_ed25519keypair_generate(
    ): Short
    fun uniffi_didtoolbox_checksum_constructor_ed25519signature_from_multibase(
    ): Short
    fun uniffi_didtoolbox_checksum_constructor_ed25519signingkey_from_multibase(
    ): Short
    fun uniffi_didtoolbox_checksum_constructor_ed25519verifyingkey_from_multibase(
    ): Short
    fun uniffi_didtoolbox_checksum_constructor_trustdidweb_create(
    ): Short
    fun uniffi_didtoolbox_checksum_constructor_trustdidweb_deactivate(
    ): Short
    fun uniffi_didtoolbox_checksum_constructor_trustdidweb_read(
    ): Short
    fun uniffi_didtoolbox_checksum_constructor_trustdidweb_update(
    ): Short
    fun uniffi_didtoolbox_checksum_constructor_trustdidwebprocessor_new(
    ): Short
    fun uniffi_didtoolbox_checksum_constructor_trustdidwebprocessor_new_with_api_key(
    ): Short
    fun ffi_didtoolbox_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: UniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 25
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_didtoolbox_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: UniffiLib) {
    if (lib.uniffi_didtoolbox_checksum_method_diddoc_get_assertion_method() != 29913.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_diddoc_get_authentication() != 34911.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_diddoc_get_capability_delegation() != 44865.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_diddoc_get_capability_invocation() != 43621.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_diddoc_get_context() != 52581.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_diddoc_get_controller() != 58020.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_diddoc_get_deactivated() != 33246.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_diddoc_get_id() != 59954.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_diddoc_get_verification_method() != 46020.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_diddocumentstate_validate() != 4769.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_diddocumentstate_validate_with_scid() != 46799.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_ed25519keypair_get_signing_key() != 65401.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_ed25519keypair_get_verifying_key() != 31026.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_ed25519keypair_sign() != 30995.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_ed25519signature_to_multibase() != 52563.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_ed25519signingkey_to_multibase() != 25405.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_ed25519verifyingkey_to_multibase() != 25116.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_trustdidweb_get_did() != 41881.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_trustdidweb_get_did_doc() != 27888.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_trustdidweb_get_did_log() != 54432.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_trustdidwebprocessor_create() != 15129.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_trustdidwebprocessor_deactivate() != 63785.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_trustdidwebprocessor_read() != 43599.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_method_trustdidwebprocessor_update() != 8040.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_constructor_diddoc_from_json() != 43211.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_constructor_diddocumentstate_from() != 24730.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_constructor_ed25519keypair_from() != 44468.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_constructor_ed25519keypair_generate() != 8955.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_constructor_ed25519signature_from_multibase() != 23579.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_constructor_ed25519signingkey_from_multibase() != 64295.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_constructor_ed25519verifyingkey_from_multibase() != 58428.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_constructor_trustdidweb_create() != 52733.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_constructor_trustdidweb_deactivate() != 22064.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_constructor_trustdidweb_read() != 26526.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_constructor_trustdidweb_update() != 36262.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_constructor_trustdidwebprocessor_new() != 14974.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_didtoolbox_checksum_constructor_trustdidwebprocessor_new_with_api_key() != 8107.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len)
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): Int {
        val sizeForLength = 4
        val sizeForString = value.length * 3
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}



// The cleaner interface for Object finalization code to run.
// This is the entry point to any implementation that we're using.
//
// The cleaner registers objects and returns cleanables, so now we are
// defining a `UniffiCleaner` with a `UniffiClenaer.Cleanable` to abstract the
// different implmentations available at compile time.
interface UniffiCleaner {
    interface Cleanable {
        fun clean()
    }

    fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable

    companion object
}

// The fallback Jna cleaner, which is available for both Android, and the JVM.
private class UniffiJnaCleaner : UniffiCleaner {
    private val cleaner = com.sun.jna.internal.Cleaner.getCleaner()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        UniffiJnaCleanable(cleaner.register(value, cleanUpTask))
}

private class UniffiJnaCleanable(
    private val cleanable: com.sun.jna.internal.Cleaner.Cleanable,
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}

// We decide at uniffi binding generation time whether we were
// using Android or not.
// There are further runtime checks to chose the correct implementation
// of the cleaner.


private fun UniffiCleaner.Companion.create(): UniffiCleaner =
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
        AndroidSystemCleaner()
    } else {
        UniffiJnaCleaner()
    }

// The SystemCleaner, available from API Level 33.
private class AndroidSystemCleaner : UniffiCleaner {
    val cleaner = android.system.SystemCleaner.cleaner()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        AndroidSystemCleanable(cleaner.register(value, cleanUpTask))
}

private class AndroidSystemCleanable(
    private val cleanable: java.lang.ref.Cleaner.Cleanable,
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}

// The base class for all UniFFI Object types.
//
// This class provides core operations for working with the Rust `Arc<T>` pointer to
// the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// the Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each `FFIObject` instance holds an opaque pointer to the underlying Rust struct.
//     Method calls need to read this pointer from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an `FFIObject` is no longer needed, its pointer should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an `FFIObject` instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so risks
//     leaking the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
//   * To mitigate many of the risks of leaking memory and use-after-free unsafety, a `Cleaner`
//     is implemented to call the destructor when the Kotlin object becomes unreachable.
//     This is done in a background thread. This is not a panacea, and client code should be aware that
//      1. the thread may starve if some there are objects that have poorly performing
//     `drop` methods or do significant work in their `drop` methods.
//      2. the thread is shared across the whole library. This can be tuned by using `android_cleaner = true`,
//         or `android = true` in the [`kotlin` section of the `uniffi.toml` file](https://mozilla.github.io/uniffi-rs/kotlin/configuration.html).
//
// If we try to implement this with mutual exclusion on access to the pointer, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the pointer, but is interrupted
//      before it can pass the pointer over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read pointer value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each `FFIObject` an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// This makes a cleaner a better alternative to _not_ calling `destroy()` as
// and when the object is finished with, but the abstraction is not perfect: if the Rust object's `drop`
// method is slow, and/or there are many objects to cleanup, and it's on a low end Android device, then the cleaner
// thread may be starved, and the app will leak memory.
//
// In this case, `destroy`ing manually may be a better solution.
//
// The cleaner can live side by side with the manual calling of `destroy`. In the order of responsiveness, uniffi objects
// with Rust peers are reclaimed:
//
// 1. By calling the `destroy` method of the object, which calls `rustObject.free()`. If that doesn't happen:
// 2. When the object becomes unreachable, AND the Cleaner thread gets to call `rustObject.free()`. If the thread is starved then:
// 3. The memory is reclaimed when the process terminates.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//
abstract class FFIObject: Disposable, AutoCloseable {

    constructor(pointer: Pointer) {
        this.pointer = pointer
    }

    /**
     * This constructor can be used to instantiate a fake object.
     *
     * **WARNING: Any object instantiated with this constructor cannot be passed to an actual Rust-backed object.**
     * Since there isn't a backing [Pointer] the FFI lower functions will crash.
     * @param noPointer Placeholder value so we can have a constructor separate from the default empty one that may be
     *   implemented for classes extending [FFIObject].
     */
    @Suppress("UNUSED_PARAMETER")
    constructor(noPointer: NoPointer) {
        this.pointer = null
    }

    protected val pointer: Pointer?
    protected abstract val cleanable: UniffiCleaner.Cleanable

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    open fun uniffiClonePointer(): Pointer {
        // Overridden by generated subclasses, the default method exists to allow users to manually
        // implement the interface
        throw RuntimeException("uniffiClonePointer not implemented")
    }

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable.clean()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithPointer(block: (ptr: Pointer) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the pointer being freed concurrently.
        try {
            return block(this.uniffiClonePointer())
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable.clean()
            }
        }
    }
}

/** Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly. */
object NoPointer


public interface DidDocInterface {
    
    fun `getAssertionMethod`(): List<VerificationMethod>
    
    fun `getAuthentication`(): List<VerificationMethod>
    
    fun `getCapabilityDelegation`(): List<VerificationMethod>
    
    fun `getCapabilityInvocation`(): List<VerificationMethod>
    
    fun `getContext`(): List<String>
    
    fun `getController`(): List<String>
    
    fun `getDeactivated`(): Boolean
    
    fun `getId`(): String
    
    fun `getVerificationMethod`(): List<VerificationMethod>
    
    companion object
}

open class DidDoc : FFIObject, DidDocInterface {

    constructor(pointer: Pointer): super(pointer)

    /**
     * This constructor can be used to instantiate a fake object.
     *
     * **WARNING: Any object instantiated with this constructor cannot be passed to an actual Rust-backed object.**
     * Since there isn't a backing [Pointer] the FFI lower functions will crash.
     * @param noPointer Placeholder value so we can have a constructor separate from the default empty one that may be
     *   implemented for classes extending [FFIObject].
     */
    constructor(noPointer: NoPointer): super(noPointer)

    override val cleanable: UniffiCleaner.Cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val pointer: Pointer?) : Runnable {
        override fun run() {
            pointer?.let { ptr ->
                uniffiRustCall { status ->
                    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_free_diddoc(ptr, status)
                }
            }
        }
    }

    override fun uniffiClonePointer(): Pointer {
        return uniffiRustCall() { status ->
            UniffiLib.INSTANCE.uniffi_didtoolbox_fn_clone_diddoc(pointer!!, status)
        }
    }

    override fun `getAssertionMethod`(): List<VerificationMethod> =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_diddoc_get_assertion_method(it,
        
        _status)
}
        }.let {
            FfiConverterSequenceTypeVerificationMethod.lift(it)
        }
    
    override fun `getAuthentication`(): List<VerificationMethod> =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_diddoc_get_authentication(it,
        
        _status)
}
        }.let {
            FfiConverterSequenceTypeVerificationMethod.lift(it)
        }
    
    override fun `getCapabilityDelegation`(): List<VerificationMethod> =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_diddoc_get_capability_delegation(it,
        
        _status)
}
        }.let {
            FfiConverterSequenceTypeVerificationMethod.lift(it)
        }
    
    override fun `getCapabilityInvocation`(): List<VerificationMethod> =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_diddoc_get_capability_invocation(it,
        
        _status)
}
        }.let {
            FfiConverterSequenceTypeVerificationMethod.lift(it)
        }
    
    override fun `getContext`(): List<String> =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_diddoc_get_context(it,
        
        _status)
}
        }.let {
            FfiConverterSequenceString.lift(it)
        }
    
    override fun `getController`(): List<String> =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_diddoc_get_controller(it,
        
        _status)
}
        }.let {
            FfiConverterSequenceString.lift(it)
        }
    
    override fun `getDeactivated`(): Boolean =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_diddoc_get_deactivated(it,
        
        _status)
}
        }.let {
            FfiConverterBoolean.lift(it)
        }
    
    override fun `getId`(): String =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_diddoc_get_id(it,
        
        _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    override fun `getVerificationMethod`(): List<VerificationMethod> =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_diddoc_get_verification_method(it,
        
        _status)
}
        }.let {
            FfiConverterSequenceTypeVerificationMethod.lift(it)
        }
    
    

    companion object {
        
        fun `fromJson`(`jsonContent`: String): DidDoc =
            DidDoc(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_constructor_diddoc_from_json(FfiConverterString.lower(`jsonContent`),_status)
})
        
    }
    
}

public object FfiConverterTypeDidDoc: FfiConverter<DidDoc, Pointer> {

    override fun lower(value: DidDoc): Pointer {
        return value.uniffiClonePointer()
    }

    override fun lift(value: Pointer): DidDoc {
        return DidDoc(value)
    }

    override fun read(buf: ByteBuffer): DidDoc {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: DidDoc) = 8

    override fun write(value: DidDoc, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}





public interface DidDocumentStateInterface {
    
    fun `validate`(): DidDoc
    
    fun `validateWithScid`(`scid`: String?): DidDoc
    
    companion object
}

open class DidDocumentState : FFIObject, DidDocumentStateInterface {

    constructor(pointer: Pointer): super(pointer)

    /**
     * This constructor can be used to instantiate a fake object.
     *
     * **WARNING: Any object instantiated with this constructor cannot be passed to an actual Rust-backed object.**
     * Since there isn't a backing [Pointer] the FFI lower functions will crash.
     * @param noPointer Placeholder value so we can have a constructor separate from the default empty one that may be
     *   implemented for classes extending [FFIObject].
     */
    constructor(noPointer: NoPointer): super(noPointer)

    override val cleanable: UniffiCleaner.Cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val pointer: Pointer?) : Runnable {
        override fun run() {
            pointer?.let { ptr ->
                uniffiRustCall { status ->
                    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_free_diddocumentstate(ptr, status)
                }
            }
        }
    }

    override fun uniffiClonePointer(): Pointer {
        return uniffiRustCall() { status ->
            UniffiLib.INSTANCE.uniffi_didtoolbox_fn_clone_diddocumentstate(pointer!!, status)
        }
    }

    override fun `validate`(): DidDoc =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_diddocumentstate_validate(it,
        
        _status)
}
        }.let {
            FfiConverterTypeDidDoc.lift(it)
        }
    
    override fun `validateWithScid`(`scid`: String?): DidDoc =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_diddocumentstate_validate_with_scid(it,
        FfiConverterOptionalString.lower(`scid`),
        _status)
}
        }.let {
            FfiConverterTypeDidDoc.lift(it)
        }
    
    

    companion object {
        
        fun `from`(`didLog`: String): DidDocumentState =
            DidDocumentState(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_constructor_diddocumentstate_from(FfiConverterString.lower(`didLog`),_status)
})
        
    }
    
}

public object FfiConverterTypeDidDocumentState: FfiConverter<DidDocumentState, Pointer> {

    override fun lower(value: DidDocumentState): Pointer {
        return value.uniffiClonePointer()
    }

    override fun lift(value: Pointer): DidDocumentState {
        return DidDocumentState(value)
    }

    override fun read(buf: ByteBuffer): DidDocumentState {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: DidDocumentState) = 8

    override fun write(value: DidDocumentState, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}





public interface Ed25519KeyPairInterface {
    
    fun `getSigningKey`(): Ed25519SigningKey
    
    fun `getVerifyingKey`(): Ed25519VerifyingKey
    
    fun `sign`(`message`: String): Ed25519Signature
    
    companion object
}

open class Ed25519KeyPair : FFIObject, Ed25519KeyPairInterface {

    constructor(pointer: Pointer): super(pointer)

    /**
     * This constructor can be used to instantiate a fake object.
     *
     * **WARNING: Any object instantiated with this constructor cannot be passed to an actual Rust-backed object.**
     * Since there isn't a backing [Pointer] the FFI lower functions will crash.
     * @param noPointer Placeholder value so we can have a constructor separate from the default empty one that may be
     *   implemented for classes extending [FFIObject].
     */
    constructor(noPointer: NoPointer): super(noPointer)

    override val cleanable: UniffiCleaner.Cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val pointer: Pointer?) : Runnable {
        override fun run() {
            pointer?.let { ptr ->
                uniffiRustCall { status ->
                    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_free_ed25519keypair(ptr, status)
                }
            }
        }
    }

    override fun uniffiClonePointer(): Pointer {
        return uniffiRustCall() { status ->
            UniffiLib.INSTANCE.uniffi_didtoolbox_fn_clone_ed25519keypair(pointer!!, status)
        }
    }

    override fun `getSigningKey`(): Ed25519SigningKey =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_ed25519keypair_get_signing_key(it,
        
        _status)
}
        }.let {
            FfiConverterTypeEd25519SigningKey.lift(it)
        }
    
    override fun `getVerifyingKey`(): Ed25519VerifyingKey =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_ed25519keypair_get_verifying_key(it,
        
        _status)
}
        }.let {
            FfiConverterTypeEd25519VerifyingKey.lift(it)
        }
    
    override fun `sign`(`message`: String): Ed25519Signature =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_ed25519keypair_sign(it,
        FfiConverterString.lower(`message`),
        _status)
}
        }.let {
            FfiConverterTypeEd25519Signature.lift(it)
        }
    
    

    companion object {
        
        fun `from`(`signingKeyMultibase`: String): Ed25519KeyPair =
            Ed25519KeyPair(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_constructor_ed25519keypair_from(FfiConverterString.lower(`signingKeyMultibase`),_status)
})
        
        fun `generate`(): Ed25519KeyPair =
            Ed25519KeyPair(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_constructor_ed25519keypair_generate(_status)
})
        
    }
    
}

public object FfiConverterTypeEd25519KeyPair: FfiConverter<Ed25519KeyPair, Pointer> {

    override fun lower(value: Ed25519KeyPair): Pointer {
        return value.uniffiClonePointer()
    }

    override fun lift(value: Pointer): Ed25519KeyPair {
        return Ed25519KeyPair(value)
    }

    override fun read(buf: ByteBuffer): Ed25519KeyPair {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: Ed25519KeyPair) = 8

    override fun write(value: Ed25519KeyPair, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}





public interface Ed25519SignatureInterface {
    
    fun `toMultibase`(): String
    
    companion object
}

open class Ed25519Signature : FFIObject, Ed25519SignatureInterface {

    constructor(pointer: Pointer): super(pointer)

    /**
     * This constructor can be used to instantiate a fake object.
     *
     * **WARNING: Any object instantiated with this constructor cannot be passed to an actual Rust-backed object.**
     * Since there isn't a backing [Pointer] the FFI lower functions will crash.
     * @param noPointer Placeholder value so we can have a constructor separate from the default empty one that may be
     *   implemented for classes extending [FFIObject].
     */
    constructor(noPointer: NoPointer): super(noPointer)

    override val cleanable: UniffiCleaner.Cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val pointer: Pointer?) : Runnable {
        override fun run() {
            pointer?.let { ptr ->
                uniffiRustCall { status ->
                    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_free_ed25519signature(ptr, status)
                }
            }
        }
    }

    override fun uniffiClonePointer(): Pointer {
        return uniffiRustCall() { status ->
            UniffiLib.INSTANCE.uniffi_didtoolbox_fn_clone_ed25519signature(pointer!!, status)
        }
    }

    override fun `toMultibase`(): String =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_ed25519signature_to_multibase(it,
        
        _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    

    companion object {
        
        fun `fromMultibase`(`multibase`: String): Ed25519Signature =
            Ed25519Signature(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_constructor_ed25519signature_from_multibase(FfiConverterString.lower(`multibase`),_status)
})
        
    }
    
}

public object FfiConverterTypeEd25519Signature: FfiConverter<Ed25519Signature, Pointer> {

    override fun lower(value: Ed25519Signature): Pointer {
        return value.uniffiClonePointer()
    }

    override fun lift(value: Pointer): Ed25519Signature {
        return Ed25519Signature(value)
    }

    override fun read(buf: ByteBuffer): Ed25519Signature {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: Ed25519Signature) = 8

    override fun write(value: Ed25519Signature, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}





public interface Ed25519SigningKeyInterface {
    
    fun `toMultibase`(): String
    
    companion object
}

open class Ed25519SigningKey : FFIObject, Ed25519SigningKeyInterface {

    constructor(pointer: Pointer): super(pointer)

    /**
     * This constructor can be used to instantiate a fake object.
     *
     * **WARNING: Any object instantiated with this constructor cannot be passed to an actual Rust-backed object.**
     * Since there isn't a backing [Pointer] the FFI lower functions will crash.
     * @param noPointer Placeholder value so we can have a constructor separate from the default empty one that may be
     *   implemented for classes extending [FFIObject].
     */
    constructor(noPointer: NoPointer): super(noPointer)

    override val cleanable: UniffiCleaner.Cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val pointer: Pointer?) : Runnable {
        override fun run() {
            pointer?.let { ptr ->
                uniffiRustCall { status ->
                    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_free_ed25519signingkey(ptr, status)
                }
            }
        }
    }

    override fun uniffiClonePointer(): Pointer {
        return uniffiRustCall() { status ->
            UniffiLib.INSTANCE.uniffi_didtoolbox_fn_clone_ed25519signingkey(pointer!!, status)
        }
    }

    override fun `toMultibase`(): String =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_ed25519signingkey_to_multibase(it,
        
        _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    

    companion object {
        
        fun `fromMultibase`(`multibase`: String): Ed25519SigningKey =
            Ed25519SigningKey(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_constructor_ed25519signingkey_from_multibase(FfiConverterString.lower(`multibase`),_status)
})
        
    }
    
}

public object FfiConverterTypeEd25519SigningKey: FfiConverter<Ed25519SigningKey, Pointer> {

    override fun lower(value: Ed25519SigningKey): Pointer {
        return value.uniffiClonePointer()
    }

    override fun lift(value: Pointer): Ed25519SigningKey {
        return Ed25519SigningKey(value)
    }

    override fun read(buf: ByteBuffer): Ed25519SigningKey {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: Ed25519SigningKey) = 8

    override fun write(value: Ed25519SigningKey, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}





public interface Ed25519VerifyingKeyInterface {
    
    fun `toMultibase`(): String
    
    companion object
}

open class Ed25519VerifyingKey : FFIObject, Ed25519VerifyingKeyInterface {

    constructor(pointer: Pointer): super(pointer)

    /**
     * This constructor can be used to instantiate a fake object.
     *
     * **WARNING: Any object instantiated with this constructor cannot be passed to an actual Rust-backed object.**
     * Since there isn't a backing [Pointer] the FFI lower functions will crash.
     * @param noPointer Placeholder value so we can have a constructor separate from the default empty one that may be
     *   implemented for classes extending [FFIObject].
     */
    constructor(noPointer: NoPointer): super(noPointer)

    override val cleanable: UniffiCleaner.Cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val pointer: Pointer?) : Runnable {
        override fun run() {
            pointer?.let { ptr ->
                uniffiRustCall { status ->
                    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_free_ed25519verifyingkey(ptr, status)
                }
            }
        }
    }

    override fun uniffiClonePointer(): Pointer {
        return uniffiRustCall() { status ->
            UniffiLib.INSTANCE.uniffi_didtoolbox_fn_clone_ed25519verifyingkey(pointer!!, status)
        }
    }

    override fun `toMultibase`(): String =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_ed25519verifyingkey_to_multibase(it,
        
        _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    

    companion object {
        
        fun `fromMultibase`(`multibase`: String): Ed25519VerifyingKey =
            Ed25519VerifyingKey(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_constructor_ed25519verifyingkey_from_multibase(FfiConverterString.lower(`multibase`),_status)
})
        
    }
    
}

public object FfiConverterTypeEd25519VerifyingKey: FfiConverter<Ed25519VerifyingKey, Pointer> {

    override fun lower(value: Ed25519VerifyingKey): Pointer {
        return value.uniffiClonePointer()
    }

    override fun lift(value: Pointer): Ed25519VerifyingKey {
        return Ed25519VerifyingKey(value)
    }

    override fun read(buf: ByteBuffer): Ed25519VerifyingKey {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: Ed25519VerifyingKey) = 8

    override fun write(value: Ed25519VerifyingKey, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}





public interface TrustDidWebInterface {
    
    fun `getDid`(): String
    
    fun `getDidDoc`(): String
    
    fun `getDidLog`(): String
    
    companion object
}

open class TrustDidWeb : FFIObject, TrustDidWebInterface {

    constructor(pointer: Pointer): super(pointer)

    /**
     * This constructor can be used to instantiate a fake object.
     *
     * **WARNING: Any object instantiated with this constructor cannot be passed to an actual Rust-backed object.**
     * Since there isn't a backing [Pointer] the FFI lower functions will crash.
     * @param noPointer Placeholder value so we can have a constructor separate from the default empty one that may be
     *   implemented for classes extending [FFIObject].
     */
    constructor(noPointer: NoPointer): super(noPointer)

    override val cleanable: UniffiCleaner.Cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val pointer: Pointer?) : Runnable {
        override fun run() {
            pointer?.let { ptr ->
                uniffiRustCall { status ->
                    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_free_trustdidweb(ptr, status)
                }
            }
        }
    }

    override fun uniffiClonePointer(): Pointer {
        return uniffiRustCall() { status ->
            UniffiLib.INSTANCE.uniffi_didtoolbox_fn_clone_trustdidweb(pointer!!, status)
        }
    }

    override fun `getDid`(): String =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_trustdidweb_get_did(it,
        
        _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    override fun `getDidDoc`(): String =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_trustdidweb_get_did_doc(it,
        
        _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    override fun `getDidLog`(): String =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_trustdidweb_get_did_log(it,
        
        _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    

    companion object {
        
        fun `create`(`url`: String, `keyPair`: Ed25519KeyPair, `allowHttp`: Boolean?): TrustDidWeb =
            TrustDidWeb(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_constructor_trustdidweb_create(FfiConverterString.lower(`url`),FfiConverterTypeEd25519KeyPair.lower(`keyPair`),FfiConverterOptionalBoolean.lower(`allowHttp`),_status)
})
        
        fun `deactivate`(`didTdw`: String, `didLog`: String, `keyPair`: Ed25519KeyPair, `allowHttp`: Boolean?): TrustDidWeb =
            TrustDidWeb(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_constructor_trustdidweb_deactivate(FfiConverterString.lower(`didTdw`),FfiConverterString.lower(`didLog`),FfiConverterTypeEd25519KeyPair.lower(`keyPair`),FfiConverterOptionalBoolean.lower(`allowHttp`),_status)
})
        
        fun `read`(`didTdw`: String, `allowHttp`: Boolean?): TrustDidWeb =
            TrustDidWeb(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_constructor_trustdidweb_read(FfiConverterString.lower(`didTdw`),FfiConverterOptionalBoolean.lower(`allowHttp`),_status)
})
        
        fun `update`(`didTdw`: String, `didLog`: String, `didDoc`: String, `keyPair`: Ed25519KeyPair, `allowHttp`: Boolean?): TrustDidWeb =
            TrustDidWeb(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_constructor_trustdidweb_update(FfiConverterString.lower(`didTdw`),FfiConverterString.lower(`didLog`),FfiConverterString.lower(`didDoc`),FfiConverterTypeEd25519KeyPair.lower(`keyPair`),FfiConverterOptionalBoolean.lower(`allowHttp`),_status)
})
        
    }
    
}

public object FfiConverterTypeTrustDidWeb: FfiConverter<TrustDidWeb, Pointer> {

    override fun lower(value: TrustDidWeb): Pointer {
        return value.uniffiClonePointer()
    }

    override fun lift(value: Pointer): TrustDidWeb {
        return TrustDidWeb(value)
    }

    override fun read(buf: ByteBuffer): TrustDidWeb {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: TrustDidWeb) = 8

    override fun write(value: TrustDidWeb, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}





public interface TrustDidWebProcessorInterface {
    
    fun `create`(`url`: String, `keyPair`: Ed25519KeyPair, `allowHttp`: Boolean?): String
    
    fun `deactivate`(`didTdw`: String, `keyPair`: Ed25519KeyPair, `allowHttp`: Boolean?): String
    
    fun `read`(`didTdw`: String, `allowHttp`: Boolean?): String
    
    fun `update`(`didTdw`: String, `didDoc`: String, `keyPair`: Ed25519KeyPair, `allowHttp`: Boolean?): String
    
    companion object
}

open class TrustDidWebProcessor : FFIObject, TrustDidWebProcessorInterface {

    constructor(pointer: Pointer): super(pointer)

    /**
     * This constructor can be used to instantiate a fake object.
     *
     * **WARNING: Any object instantiated with this constructor cannot be passed to an actual Rust-backed object.**
     * Since there isn't a backing [Pointer] the FFI lower functions will crash.
     * @param noPointer Placeholder value so we can have a constructor separate from the default empty one that may be
     *   implemented for classes extending [FFIObject].
     */
    constructor(noPointer: NoPointer): super(noPointer)
    constructor() :
        this(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_constructor_trustdidwebprocessor_new(_status)
})

    override val cleanable: UniffiCleaner.Cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val pointer: Pointer?) : Runnable {
        override fun run() {
            pointer?.let { ptr ->
                uniffiRustCall { status ->
                    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_free_trustdidwebprocessor(ptr, status)
                }
            }
        }
    }

    override fun uniffiClonePointer(): Pointer {
        return uniffiRustCall() { status ->
            UniffiLib.INSTANCE.uniffi_didtoolbox_fn_clone_trustdidwebprocessor(pointer!!, status)
        }
    }

    override fun `create`(`url`: String, `keyPair`: Ed25519KeyPair, `allowHttp`: Boolean?): String =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_trustdidwebprocessor_create(it,
        FfiConverterString.lower(`url`),FfiConverterTypeEd25519KeyPair.lower(`keyPair`),FfiConverterOptionalBoolean.lower(`allowHttp`),
        _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    override fun `deactivate`(`didTdw`: String, `keyPair`: Ed25519KeyPair, `allowHttp`: Boolean?): String =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_trustdidwebprocessor_deactivate(it,
        FfiConverterString.lower(`didTdw`),FfiConverterTypeEd25519KeyPair.lower(`keyPair`),FfiConverterOptionalBoolean.lower(`allowHttp`),
        _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    override fun `read`(`didTdw`: String, `allowHttp`: Boolean?): String =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_trustdidwebprocessor_read(it,
        FfiConverterString.lower(`didTdw`),FfiConverterOptionalBoolean.lower(`allowHttp`),
        _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    override fun `update`(`didTdw`: String, `didDoc`: String, `keyPair`: Ed25519KeyPair, `allowHttp`: Boolean?): String =
        callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_method_trustdidwebprocessor_update(it,
        FfiConverterString.lower(`didTdw`),FfiConverterString.lower(`didDoc`),FfiConverterTypeEd25519KeyPair.lower(`keyPair`),FfiConverterOptionalBoolean.lower(`allowHttp`),
        _status)
}
        }.let {
            FfiConverterString.lift(it)
        }
    
    

    companion object {
        
        fun `newWithApiKey`(`apiKey`: String): TrustDidWebProcessor =
            TrustDidWebProcessor(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_didtoolbox_fn_constructor_trustdidwebprocessor_new_with_api_key(FfiConverterString.lower(`apiKey`),_status)
})
        
    }
    
}

public object FfiConverterTypeTrustDidWebProcessor: FfiConverter<TrustDidWebProcessor, Pointer> {

    override fun lower(value: TrustDidWebProcessor): Pointer {
        return value.uniffiClonePointer()
    }

    override fun lift(value: Pointer): TrustDidWebProcessor {
        return TrustDidWebProcessor(value)
    }

    override fun read(buf: ByteBuffer): TrustDidWebProcessor {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: TrustDidWebProcessor) = 8

    override fun write(value: TrustDidWebProcessor, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}



data class Jwk (
    var `alg`: String?, 
    var `kid`: String?, 
    var `kty`: String?, 
    var `crv`: String?, 
    var `x`: String?, 
    var `y`: String?
) {
    
    companion object
}

public object FfiConverterTypeJwk: FfiConverterRustBuffer<Jwk> {
    override fun read(buf: ByteBuffer): Jwk {
        return Jwk(
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: Jwk) = (
            FfiConverterOptionalString.allocationSize(value.`alg`) +
            FfiConverterOptionalString.allocationSize(value.`kid`) +
            FfiConverterOptionalString.allocationSize(value.`kty`) +
            FfiConverterOptionalString.allocationSize(value.`crv`) +
            FfiConverterOptionalString.allocationSize(value.`x`) +
            FfiConverterOptionalString.allocationSize(value.`y`)
    )

    override fun write(value: Jwk, buf: ByteBuffer) {
            FfiConverterOptionalString.write(value.`alg`, buf)
            FfiConverterOptionalString.write(value.`kid`, buf)
            FfiConverterOptionalString.write(value.`kty`, buf)
            FfiConverterOptionalString.write(value.`crv`, buf)
            FfiConverterOptionalString.write(value.`x`, buf)
            FfiConverterOptionalString.write(value.`y`, buf)
    }
}



data class VerificationMethod (
    var `id`: String, 
    var `controller`: String, 
    var `verificationType`: String, 
    var `publicKeyMultibase`: String?, 
    var `publicKeyJwk`: Jwk?
) {
    
    companion object
}

public object FfiConverterTypeVerificationMethod: FfiConverterRustBuffer<VerificationMethod> {
    override fun read(buf: ByteBuffer): VerificationMethod {
        return VerificationMethod(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalTypeJwk.read(buf),
        )
    }

    override fun allocationSize(value: VerificationMethod) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`controller`) +
            FfiConverterString.allocationSize(value.`verificationType`) +
            FfiConverterOptionalString.allocationSize(value.`publicKeyMultibase`) +
            FfiConverterOptionalTypeJwk.allocationSize(value.`publicKeyJwk`)
    )

    override fun write(value: VerificationMethod, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`controller`, buf)
            FfiConverterString.write(value.`verificationType`, buf)
            FfiConverterOptionalString.write(value.`publicKeyMultibase`, buf)
            FfiConverterOptionalTypeJwk.write(value.`publicKeyJwk`, buf)
    }
}




public object FfiConverterOptionalBoolean: FfiConverterRustBuffer<Boolean?> {
    override fun read(buf: ByteBuffer): Boolean? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterBoolean.read(buf)
    }

    override fun allocationSize(value: Boolean?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterBoolean.allocationSize(value)
        }
    }

    override fun write(value: Boolean?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterBoolean.write(value, buf)
        }
    }
}




public object FfiConverterOptionalString: FfiConverterRustBuffer<String?> {
    override fun read(buf: ByteBuffer): String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: String?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




public object FfiConverterOptionalTypeJwk: FfiConverterRustBuffer<Jwk?> {
    override fun read(buf: ByteBuffer): Jwk? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeJwk.read(buf)
    }

    override fun allocationSize(value: Jwk?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterTypeJwk.allocationSize(value)
        }
    }

    override fun write(value: Jwk?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeJwk.write(value, buf)
        }
    }
}




public object FfiConverterSequenceString: FfiConverterRustBuffer<List<String>> {
    override fun read(buf: ByteBuffer): List<String> {
        val len = buf.getInt()
        return List<String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<String>): Int {
        val sizeForLength = 4
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




public object FfiConverterSequenceTypeVerificationMethod: FfiConverterRustBuffer<List<VerificationMethod>> {
    override fun read(buf: ByteBuffer): List<VerificationMethod> {
        val len = buf.getInt()
        return List<VerificationMethod>(len) {
            FfiConverterTypeVerificationMethod.read(buf)
        }
    }

    override fun allocationSize(value: List<VerificationMethod>): Int {
        val sizeForLength = 4
        val sizeForItems = value.map { FfiConverterTypeVerificationMethod.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<VerificationMethod>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.forEach {
            FfiConverterTypeVerificationMethod.write(it, buf)
        }
    }
}

